openapi: 3.0.3
info:
  title: API de Microservicio de Retiros en Dólares (USD)
  description: |
    Especificación OpenAPI 3.0 para el Microservicio de Retiros en Dólares USD (`service-retire-usd`).
    Desarrollado con Arquitectura Hexagonal, Principios SOLID, NestJS, TypeORM, PostgreSQL y mensajería RabbitMQ.
  version: 1.0.0
servers:
  - url: http://localhost:3004
    description: Servidor Local de Desarrollo (Docker Container)

paths:
  /retiros:
    post:
      summary: Crear una nueva solicitud de retiro en Dólares (USD)
      description: Registra una nueva solicitud de retiro en estado PENDIENTE y emite el evento 'withdrawal.requested' a RabbitMQ.
      operationId: crearRetiro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrearRetiroDto'
      responses:
        '201':
          description: Solicitud de retiro creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetiroRespuestaDto'
        '400':
          description: Datos de entrada inválidos o límites violados ($1 - $10,000 USD)

  /retiros/usuario/{usuarioId}:
    get:
      summary: Obtener historial de retiros por ID de usuario
      description: Retorna la lista completa de solicitudes de retiro asociadas al UUID de un usuario.
      operationId: obtenerPorUsuarioId
      parameters:
        - name: usuarioId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          example: d3b07384-d113-46e4-a123-561234567890
      responses:
        '200':
          description: Lista de retiros obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RetiroRespuestaDto'

  /retiros/{id}:
    get:
      summary: Consultar detalle de un retiro por ID único
      description: Retorna la información detallada de una transacción de retiro específica.
      operationId: obtenerPorId
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          example: 69354f24-a068-44d5-a222-22f76e370722
      responses:
        '200':
          description: Transacción de retiro encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetiroRespuestaDto'
        '404':
          description: Retiro no encontrado

components:
  schemas:
    CrearRetiroDto:
      type: object
      required:
        - usuarioId
        - montoUSD
        - codigoBanco
        - cuentaDestino
      properties:
        usuarioId:
          type: string
          format: uuid
          example: d3b07384-d113-46e4-a123-561234567890
        montoUSD:
          type: number
          format: double
          minimum: 1.00
          maximum: 10000.00
          example: 150.50
        codigoBanco:
          type: string
          example: CHASEUS33XXX
        cuentaDestino:
          type: string
          example: 987654321012
        tipoCuenta:
          type: string
          default: AHORROS
          example: AHORROS

    RetiroRespuestaDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 69354f24-a068-44d5-a222-22f76e370722
        usuarioId:
          type: string
          format: uuid
          example: d3b07384-d113-46e4-a123-561234567890
        montoUSD:
          type: number
          example: 150.50
        moneda:
          type: string
          example: USD
        codigoBanco:
          type: string
          example: CHASEUS33XXX
        cuentaDestino:
          type: string
          example: 987654321012
        tipoCuenta:
          type: string
          example: AHORROS
        estado:
          type: string
          enum: [PENDIENTE, EN_PROCESO, COMPLETADO, RECHAZADO, FALLIDO]
          example: PENDIENTE
        referenciaBancaria:
          type: string
          nullable: true
          example: ACH-781784
        razonFallo:
          type: string
          nullable: true
          example: null
        fechaCreacion:
          type: string
          format: date-time
          example: 2026-10-06T22:51:30.507Z
